apiVersion: 1

datasources:
  - name: Cassandra-Legacy
    uid: cassandra
    type: hadesarchitect-cassandra-datasource
    access: proxy
    url: cassandra:9042
    isDefault: false
    jsonData:
      keyspace: taasim
      consistency: LOCAL_ONE
