apiVersion: 1

datasources:
  - name: Cassandra
    type: hadesarchitect-cassandra-datasource
    uid: TaaSim-Cassandra
    access: proxy
    url: "cassandra:9042"
    jsonData:
      keyspace: taasim
      consistency: ONE
    isDefault: true
    editable: true
